language: node_js
node_js:
  - "6.6"
  
# to empty the cache go to https://travis-ci.com/crewmeister/browser-app/caches
cache:
  directories:
  - node_modules

after_success:
  - chmod +x ./scripts/*.sh
  - npm run build

deploy:
  provider: script
  script: ./scripts/deploy-to-ghpages.sh
  skip_cleanup: true
  branch: master

env:
 global:
 - GH_REF: github.com/cosmowiki/cosmowiki.git
