language: node_js
node_js:
  - "6.6"
  
# to empty the cache go to https://travis-ci.com/crewmeister/browser-app/caches
cache:
  directories:
  - node_modules

after_success:
  - chmod +x ./scripts/*.sh
  - ./scripts/build.sh

deploy:
  provider: script
  script: ./scripts/deploy-to-ghpages.sh
  skip_cleanup: true
  branch: master

env:
 global:
 - GH_REF: github.com/cosmowiki/cosmowiki.git
 - secure: rt8wJqtbR+ylu0K32pvjkr2D5B/tQam+FbbgFDO4FYTUP6+YJNeiO+rHuLt2KbkmJ00S9n6JnRCHRbELi4vDGfCtWep7Zh5rI8Ur28cN/s7nwZf8eY4tZaFKqk1CUIdlXkXtwnPPlSwGNBdW6S7er2GnGFQOv7IYqOpMErYQKvPhHYIuF4jvltuub+FioiTmFkFTCsvUSSDAbhmZfwMkjOUNGwt85KatgPFI0wqtx7mSP4ColpPhTtxLt3gRqbFnVY8oszFDXwzNbu2JzK5C3/+prVNSHJdNi6Ln8PqXvcOdal8mkaflEGlzCdgk1btDgofqBQBqOOdYsi92jMEoQ5Xj/W6AmY8lFWE7nGC/7JPlN3PCyu4rVJMiLCBlPftv2JJjluHkwfgUTmT3AwBpyKJojtCWBbYI+BsS0s6CiZ0vbl/4dZrRAF3WzYP8B12j8vC3R3Pv5rUXo40OwEXl7suWQtSTHBsBjo++8B0nYDP0jNuKiBvTdMWEwR35OwM0Ik5fqAl5pDTot//mgLVhFQwJBXmyikUZM8FDyrq/Ku/fO/HKPLEVDWT7JG1b07rqOm3uT+9y9l6v9qHx/BUZPM7qkj93hB/RNbiL6UCU7C1dPqWzRF3AU3XlnJcuwulD3Lhf3puZMFxA0b4cSbDkWX+9BBzbx9TOAE8/YQfWFm4=
